plugins {
    id 'net.fabricmc.fabric-loom' version "${loom_version}"
    id "dev.ithundxr.silk" version "1.0.1"
    id "me.modmuss50.mod-publish-plugin" version "1.1.0"
}

version = project.mod_version
group = project.maven_group

base {
    archivesName = project.archives_base_name
}

repositories {
    maven { url = "https://maven.terraformersmc.com/releases/" }
    maven { url = "https://maven.ladysnake.org/releases" }
    maven { url = "https://maven.blamejared.com/" }
    maven { url = "https://modmaven.dev" }
    maven { url = "https://maven.isxander.dev/releases" }
    maven { url = "https://maven.nucleoid.xyz/releases" }
    exclusiveContent {
        forRepository {
            maven {
                name = "Modrinth"
                url = "https://api.modrinth.com/maven"
            }
        }
        filter {
            includeGroup "maven.modrinth"
        }
    }
}

loom {
    mods {
        "umapyoi" {
            sourceSet sourceSets.main
        }
    }

    accessWidenerPath = file("src/main/resources/umapyoi.classtweaker")
}

fabricApi {
    configureDataGeneration() {
        client = true
    }
}

sourceSets {
    main {
        resources {
            srcDirs += [
                    'src/main/generated'
            ]
        }
    }
}

dependencies {
    // To change the versions see the gradle.properties file
    minecraft "com.mojang:minecraft:${project.minecraft_version}"
    implementation "net.fabricmc:fabric-loader:${project.loader_version}"

    // Fabric API. This is technically optional, but you probably want it anyway.
    implementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_version}"

    implementation "eu.pb4:trinkets:${project.trinkets_version}"

    // compile against the JEI API but do not include it at runtime
    compileOnlyApi("mezz.jei:jei-${project.jei_minecraft_version}-common-api:${project.jei_version}")
    compileOnlyApi("mezz.jei:jei-${project.jei_minecraft_version}-fabric-api:${project.jei_version}")
    // at runtime, use the full JEI jar for Fabric
    runtimeOnly("mezz.jei:jei-${project.jei_minecraft_version}-fabric:${project.jei_version}")

    implementation "dev.isxander:yet-another-config-lib:${project.yacl_version}"
    implementation "com.terraformersmc:modmenu:${project.modmenu_version}"

    implementation "com.google.code.findbugs:jsr305:3.0.2"
}

processResources {
    inputs.property "version", project.version

    filesMatching("fabric.mod.json") {
        expand "version": project.version
    }
}

tasks.withType(JavaCompile).configureEach {
    it.options.release = 25
}

java {
    // Loom will automatically attach sourcesJar to a RemapSourcesJar task and to the "build" task
    // if it is present.
    // If you remove this line, sources will not be generated.
    withSourcesJar()

    sourceCompatibility = JavaVersion.VERSION_25
    targetCompatibility = JavaVersion.VERSION_25
}

tasks.jar {
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
}

tasks.sourcesJar {
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
}

tasks.processResources {
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
}

jar {
    inputs.property "archivesName", project.base.archivesName

    from("LICENSE") {
        rename { "${it}_${project.base.archivesName.get()}"}
    }
}

publishMods {
    file = jar.archiveFile
    displayName = "Umapyoi Fabricated $mod_version"
    type = STABLE
    changelog = silk.changelog
    modLoaders.add("fabric")

    modrinth {
        accessToken = providers.gradleProperty("MODRINTH_TOKEN")
        projectId = "x1Rd7p5W"
        minecraftVersions.add(minecraft_version)
        project.publish_mods_extra_versions.split(",").each { minecraftVersions.add(it.trim()) }

        requires("fabric-api")
        requires("trinkets-updated")
        requires("yacl")
        optional("modonomicon")
        optional("create-fly")
    }

    curseforge {
        accessToken = providers.gradleProperty("CURSEFORGE_TOKEN")
        projectId = "1414857"
        minecraftVersions.add(minecraft_version)
        project.publish_mods_extra_versions.split(",").each { minecraftVersions.add(it.trim()) }

        clientRequired = true
        serverRequired = true

        requires("fabric-api")
        requires("trinkets-updated")
        requires("yacl")
        optional("modonomicon")
        optional("create-fly")
    }
}