# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

modid=umapyoi

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=1.21.10
parchment_mappings=1.21.10:2025.10.12
loader_version=0.18.3
loom_version=1.14-SNAPSHOT

#Fabric api
fabric_version=0.138.4+1.21.10

# Mod Properties
mod_version=1.12.72-1.21.10+fabric.14
maven_group=net.tracen
archives_base_name=umapyoi

# Dependencies
jei_version=26.2.0.30
jei_minecraft_version=1.21.10
owo_version=0.12.24+1.21.9
# Canary 3.11.0-1.21.10-rc1
trinkets_version=ctuA7Kxo
cca_version=7.1.0-beta.1