# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

modid=umapyoi

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=1.20.4
parchment_mappings=1.20.4:2024.04.14
loader_version=0.18.3
loom_version=1.14-SNAPSHOT

#Fabric api
fabric_version=0.97.3+1.20.4

# Mod Properties
mod_version=1.12.72-1.20.4+fabric.13
maven_group=net.tracen
archives_base_name=umapyoi

# Dependencies
jei_version=17.3.1.5
owo_version=0.12.6+1.20.3
trinkets_version=3.8.1