# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

modid=umapyoi

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=26.1.2
loader_version=0.19.1
loom_version=1.16-SNAPSHOT

#Fabric api
fabric_version=0.145.4+26.1.2

# Mod Properties
mod_version=1.12.72-26.1.2+fabric.15
maven_group=net.tracen
archives_base_name=umapyoi
publish_mods_extra_versions=26.1,26.1.1

# Dependencies
jei_version=29.5.0.24
jei_minecraft_version=26.1.2
owo_version=0.13.0+26.1
trinkets_version=4.0.0-alpha.7+26.1