package net.tracen.umapyoi.data.builtin;

import net.minecraft.resources.ResourceKey;
import net.minecraft.resources.ResourceLocation;
import net.tracen.umapyoi.Umapyoi;
import net.tracen.umapyoi.registry.training.card.SupportCard;

/**
 * Data is provided by the builtin datapack which is generated by upstream's datagen.
 * The actual data is not included here (please use UmapyoiAPI#getSupportCardRegistry)
 */
public class SupportCardRegistry {

    public static final ResourceKey<SupportCard> R_KITASANBLACK = register("r_kitasan_black");
    public static final ResourceKey<SupportCard> R_SUPERCREEK = register("r_super_creek");
    public static final ResourceKey<SupportCard> R_OGURICAP = register("r_oguri_cap");
    public static final ResourceKey<SupportCard> R_KS_MIRACLE = register("r_ks_miracle");
    public static final ResourceKey<SupportCard> R_AGNUS_TACHYON = register("r_agnus_tachyon");

    public static final ResourceKey<SupportCard> R_TURF_TRAINING = register("r_turf_training");
    public static final ResourceKey<SupportCard> R_DIRT_TRAINING = register("r_dirt_training");
    public static final ResourceKey<SupportCard> R_SNOW_TRAINING = register("r_snow_training");


    public static final ResourceKey<SupportCard> BASIC_SPEED_CARD = register("basic_speed_card");
    public static final ResourceKey<SupportCard> BASIC_STAMINA_CARD = register("basic_stamina_card");
    public static final ResourceKey<SupportCard> BASIC_STRENGTH_CARD = register("basic_strength_card");
    public static final ResourceKey<SupportCard> BASIC_GUTS_CARD = register("basic_guts_card");
    public static final ResourceKey<SupportCard> BASIC_WISDOM_CARD = register("basic_wisdom_card");

    public static final ResourceKey<SupportCard> ADV_SPEED_CARD = register("adv_speed_card");
    public static final ResourceKey<SupportCard> ADV_STAMINA_CARD = register("adv_stamina_card");
    public static final ResourceKey<SupportCard> ADV_STRENGTH_CARD = register("adv_strength_card");
    public static final ResourceKey<SupportCard> ADV_GUTS_CARD = register("adv_guts_card");
    public static final ResourceKey<SupportCard> ADV_WISDOM_CARD = register("adv_wisdom_card");

    public static final ResourceKey<SupportCard> SPEED_MASTER_CARD = register("speed_master_card");
    public static final ResourceKey<SupportCard> STAMINA_MASTER_CARD = register("stamina_master_card");
    public static final ResourceKey<SupportCard> STRENGTH_MASTER_CARD = register("strength_master_card");
    public static final ResourceKey<SupportCard> GUTS_MASTER_CARD = register("guts_master_card");
    public static final ResourceKey<SupportCard> WISDOM_MASTER_CARD = register("wisdom_master_card");

    public static final ResourceKey<SupportCard> SSR_KITASANBLACK = register("ssr_kitasan_black");
    public static final ResourceKey<SupportCard> SSR_SUPERCREEK = register("ssr_super_creek");
    public static final ResourceKey<SupportCard> SSR_OGURICAP = register("ssr_oguri_cap");
    public static final ResourceKey<SupportCard> SSR_KS_MIRACLE = register("ssr_ks_miracle");
    public static final ResourceKey<SupportCard> SR_AGNUS_TACHYON = register("sr_agnus_tachyon");
    public static final ResourceKey<SupportCard> SSR_AGNUS_TACHYON = register("ssr_agnus_tachyon");

    public static final ResourceKey<SupportCard> SSR_FINE_MOTION = register("ssr_fine_motion");

    public static final ResourceKey<SupportCard> SSR_RUDOLF_G = register("ssr_g_rudolf");
    public static final ResourceKey<SupportCard> SSR_MEJIRO_RAMONU_W = register("ssr_w_mejiro_ramonu");


    public static final ResourceKey<SupportCard> R_ACUPUNCTUIST = register("r_acupunctuist");
    public static final ResourceKey<SupportCard> SSR_ACUPUNCTUIST = register("ssr_acupunctuist");
    public static final ResourceKey<SupportCard> SSR_THREE_GODDESSES = register("ssr_three_goddesses");
    public static final ResourceKey<SupportCard> SSR_TEAM_SIRIUS = register("ssr_team_sirius");
    public static final ResourceKey<SupportCard> SSR_ANIME_MAIN = register("ssr_anime_main");
    public static final ResourceKey<SupportCard> SSR_ORFEVRE = register("ssr_orfevre");

    public static final ResourceKey<SupportCard> SSR_NEO_UNIVERSE_WIDSOM = register("ssr_neo_universe_wisdom");
    public static final ResourceKey<SupportCard> SSR_MEJIRO_MCQUEEN_STAMINA = register("ssr_mejiro_mcqueen_stamina");
    public static final ResourceKey<SupportCard> R_TM_OPERA = register("r_tm_opera");

    public static final ResourceKey<SupportCard> SSR_SATONO_DIAMOND_STAMINA = register("ssr_satono_diamond_stamina");
    public static final ResourceKey<SupportCard> SSR_KIRYUUIN_AOI = register("ssr_kiryuuin_aoi");

    private static ResourceKey<SupportCard> register(String id) {
        ResourceKey<SupportCard> loc = ResourceKey.create(SupportCard.REGISTRY_KEY, ResourceLocation.fromNamespaceAndPath(Umapyoi.MODID, id));
        return loc;
    }
}
