package net.tracen.umapyoi.data.builtin;

import net.minecraft.resources.Identifier;
import net.minecraft.resources.ResourceKey;
import net.tracen.umapyoi.Umapyoi;
import net.tracen.umapyoi.registry.umadata.UmaData;

/**
 * Data is provided by the builtin datapack which is generated by upstream's datagen.
 * The actual data is not included here (please use UmapyoiAPI#getUmaDataRegistry)
 */
public class UmaDataRegistry {

    public static final ResourceKey<UmaData> COMMON_UMA = register("common_uma");
    public static final ResourceKey<UmaData> COMMON_UMA_A = register("common_uma_a");
    public static final ResourceKey<UmaData> COMMON_UMA_B = register("common_uma_b");
    public static final ResourceKey<UmaData> COMMON_UMA_C = register("common_uma_c");
    public static final ResourceKey<UmaData> GOLD_SHIP = register("gold_ship");
    public static final ResourceKey<UmaData> SPECIAL_WEEK = register("special_week");
    public static final ResourceKey<UmaData> TOKAI_TEIO = register("tokai_teio");
    public static final ResourceKey<UmaData> OGURI_CAP = register("oguri_cap");
    public static final ResourceKey<UmaData> SAKURA_CHIYONO_O = register("sakura_chiyono_o");
    public static final ResourceKey<UmaData> OGURI_CAP_XMAS = register("oguri_cap_xmas");
    public static final ResourceKey<UmaData> AGNUS_TACHYON = register("agnus_tachyon");
    public static final ResourceKey<UmaData> HARU_URARA = register("haru_urara");
    public static final ResourceKey<UmaData> TAMAMO_CROSS = register("tamamo_cross");
    public static final ResourceKey<UmaData> SEIUN_SKY = register("seiun_sky");
    public static final ResourceKey<UmaData> MATIKANEFUKUKITARU = register("matikanefukukitaru");
    public static final ResourceKey<UmaData> RICE_SHOWER = register("rice_shower");
    public static final ResourceKey<UmaData> VODKA = register("vodka");
    public static final ResourceKey<UmaData> SAKURA_BAKUSHIN_O = register("sakura_bakushin_o");
    public static final ResourceKey<UmaData> MANHATTAN_CAFE = register("manhattan_cafe");
    public static final ResourceKey<UmaData> MEJIRO_ARDAN = register("mejiro_ardan");
    public static final ResourceKey<UmaData> DAITAKU_HELIOS = register("daitaku_helios");
    public static final ResourceKey<UmaData> SWEEP_TOSHO = register("sweep_tosho");
    public static final ResourceKey<UmaData> GOLD_CITY = register("gold_city");
    public static final ResourceKey<UmaData> GOLD_SHIP_WATER = register("gold_ship_water");
    public static final ResourceKey<UmaData> MR_CB = register("mr_cb");
    public static final ResourceKey<UmaData> GRASS_WONDER = register("grass_wonder");
    public static final ResourceKey<UmaData> CURREN_CHAN = register("curren_chan");
    public static final ResourceKey<UmaData> SILENCE_SUZUKA = register("silence_suzuka");
    public static final ResourceKey<UmaData> TAMAMO_CROSS_FESTIVAL = register("tamamo_cross_festival");
    public static final ResourceKey<UmaData> ASTON_MACHAN = register("aston_machan");
    public static final ResourceKey<UmaData> KITASAN_BLACK = register("kitasan_black");
    public static final ResourceKey<UmaData> SATONO_DIAMOND = register("satono_diamond");
    public static final ResourceKey<UmaData> NICE_NATURE = register("nice_nature");
    public static final ResourceKey<UmaData> MAYANO_TOP_GUN = register("mayano_top_gun");
    public static final ResourceKey<UmaData> NEO_UNIVERSE = register("neo_universe");
    public static final ResourceKey<UmaData> MEISHO_DOTOU = register("meisho_dotou");
    public static final ResourceKey<UmaData> TAIKI_SHUTTLE = register("taiki_shuttle");
    public static final ResourceKey<UmaData> CURREN_CHAN_DRESS = register("curren_chan_dress");
    public static final ResourceKey<UmaData> MEJIRO_MCQUEEN = register("mejiro_mcqueen");
    public static final ResourceKey<UmaData> COPANO_RICKEY = register("copano_rickey");

    public static final ResourceKey<UmaData> SYMBOLI_RUDOLF = register("symboli_rudolf");
    public static final ResourceKey<UmaData> NARITA_TOP_ROAD = register("narita_top_road");
    public static final ResourceKey<UmaData> VENUS_PARK = register("venus_park");

    public static final ResourceKey<UmaData> AGNUS_TACHYON_SWIM = register("agnus_tachyon_swim");
    public static final ResourceKey<UmaData> MIHONO_BOURBON = register("mihono_bourbon");
    public static final ResourceKey<UmaData> MATIKANETANNHAUSER = register("matikanetannhauser");
    public static final ResourceKey<UmaData> KAWAKAMI_PRINCESS = register("kawakami_princess");
    public static final ResourceKey<UmaData> TWIN_TURBO = register("twinturbo");
    public static final ResourceKey<UmaData> LITTLE_COCON = register("little_cocon");
    public static final ResourceKey<UmaData> SAKURA_LAUREL = register("sakura_laurel");
    public static final ResourceKey<UmaData> FINE_MOTION = register("fine_motion");
    public static final ResourceKey<UmaData> TM_OPERA_O = register("tm_opera_o");
    public static final ResourceKey<UmaData> ADMIRE_VEGA = register("admire_vega");
    public static final ResourceKey<UmaData> JUNGLE_POCKET = register("jungle_pocket");
    public static final ResourceKey<UmaData> NARITA_TAISHIN = register("narita_taishin");
    public static final ResourceKey<UmaData> GOLD_CITY_AUTUMN = register("gold_city_autumn");
    public static final ResourceKey<UmaData> GRASS_WONDER_UMANET = register("grass_wonder_umanet");
    public static final ResourceKey<UmaData> SATONO_DIAMOND_FRENCH = register("satono_diamond_french");
    public static final ResourceKey<UmaData> SYAMEIMARU_ZHENG = register("syameimaru_zheng");
    public static final ResourceKey<UmaData> DUMNHEINT = register("dumnheint");
    public static final ResourceKey<UmaData> DARLEY_ARABIAN = register("darley_arabian");
    public static final ResourceKey<UmaData> GODOLPHIN_BARB = register("godolphin_barb");
    public static final ResourceKey<UmaData> BYERLEY_TURK = register("byerley_turk");
    public static final ResourceKey<UmaData> SMART_FALCON = register("smart_falcon");
    public static final ResourceKey<UmaData> MANHATTAN_CAFE_VALENTINE = register("manhattan_cafe_valentine");
    public static final ResourceKey<UmaData> HISHI_MIRACLE = register("hishi_miracle");
    public static final ResourceKey<UmaData> DAIWA_SCARLET = register("daiwa_scarlet");
    public static final ResourceKey<UmaData> WIN_VARIATION = register("win_variation");

    public static final ResourceKey<UmaData> EL_CONDOR_PASA = register("el_condor_pasa");

    public static final ResourceKey<UmaData> HOKKO_TARUMAE = register("hokko_tarumae");
    public static final ResourceKey<UmaData> KING_HALO = register("king_halo");
    public static final ResourceKey<UmaData> KING_HALO_WEDDING = register("king_halo_wedding");
    public static final ResourceKey<UmaData> MATIKANETANNHAUSER_SPORTS = register("matikanetannhauser_sports");

    public static final ResourceKey<UmaData> CHEVAL_GRAND = register("cheval_grand");
    public static final ResourceKey<UmaData> VERXINA = register("verxina");
    public static final ResourceKey<UmaData> VIVLOS = register("vivlos");

    public static final ResourceKey<UmaData> FUJI_KISEKI = register("fuji_kiseki");
    public static final ResourceKey<UmaData> FUJIMASA_MARCH = register("fujimasa_march");

    public static final ResourceKey<UmaData> HOKKO_TARUMAE_SWIM = register("hokko_tarumae_swim");

    public static final ResourceKey<UmaData> MEJIRO_PALMER = register("mejiro_palmer");
    public static final ResourceKey<UmaData> TRANSCEND = register("transcend");
    public static final ResourceKey<UmaData> DURANDAL = register("durandal");
    public static final ResourceKey<UmaData> CALSTONE_LIGHT_O = register("calstone_light_o");

    public static final ResourceKey<UmaData> DAIICHI_RUBY = register("daiichi_ruby");

    public static final ResourceKey<UmaData> KATSURAGI_ACE = register("katsuragi_ace");
    public static final ResourceKey<UmaData> HAPPY_MEEK = register("happy_meek");
    public static final ResourceKey<UmaData> STILL_IN_LOVE = register("still_in_love");

    public static final ResourceKey<UmaData> RHEIN_KRAFT = register("rhein_kraft");

    public static final ResourceKey<UmaData> BUENA_VISTA = register("buena_vista");

    public static final ResourceKey<UmaData> KS_MIRACLE = register("ks_miracle");
    public static final ResourceKey<UmaData> EISHIN_FLASH = register("eishin_flash");

    public static final ResourceKey<UmaData> AGNES_DIGITAL = register("agnes_digital");

    public static final ResourceKey<UmaData> YAMANIN_ZEPHYR = register("yamanin_zephyr");
    public static final ResourceKey<UmaData> SATONO_CROWN = register("satono_crown");

    public static final ResourceKey<UmaData> MIYA_YOMOGI = register("miya_yomogi");

    public static final ResourceKey<UmaData> ALMOND_EYE = register("almond_eye");
    public static final ResourceKey<UmaData> FUSAICHI_PANDORA = register("fusaichi_pandora");

    public static final ResourceKey<UmaData> MEJIRO_RYAN = register("mejiro_ryan");
    public static final ResourceKey<UmaData> TYCHE = register("tyche");

    public static final ResourceKey<UmaData> NICE_NATURE_CHEER = register("nice_nature_cheer");

    public static final ResourceKey<UmaData> HISHI_AKEBONO = register("hishi_akebono");
    public static final ResourceKey<UmaData> SHENONE_SUZUNA = register("shenone_suzuna");

    public static final ResourceKey<UmaData> VIVLOS_SWIM = register("vivlos_swim");

    public static final ResourceKey<UmaData> MARUZENSKY = register("maruzensky");

    public static final ResourceKey<UmaData> AGNES_DIGITAL_KYOSHI = register("agnes_digital_kyoshi");
    public static final ResourceKey<UmaData> DANTSU_FLAME = register("dantsu_flame");

    private static ResourceKey<UmaData> register(String id) {
        ResourceKey<UmaData> loc = ResourceKey.create(UmaData.REGISTRY_KEY, Identifier.fromNamespaceAndPath(Umapyoi.MODID, id));
        return loc;
    }
}
